name: knowledge-visualization

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: knovion-chat-store
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgvector:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - knovion-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatbot-api:
    build: .
    container_name: knovion-chatbot-api
    environment:
      FRONTEND_URL: ${FRONTEND_URL}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

    ports:
      - "8000:8000"
    depends_on:
      - pgvector
    restart: unless-stopped
    networks:
      - knovion-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  knovion-network:
    driver: bridge

volumes:
  pgvector:
    name: knovion-chat-store